// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi;

#nullable disable

namespace WEBAPI.Migrations
{
    [DbContext(typeof(EmployeesContext))]
    [Migration("20230622194913_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.5.23280.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.tblArea", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("costcenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("costcenterId");

                    b.ToTable("Area", (string)null);

                    b.HasData(
                        new
                        {
                            id = new Guid("d341691c-112e-11ee-be56-0242ac120002"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 291, DateTimeKind.Local).AddTicks(8940),
                            code = "Aut1234",
                            costcenterId = new Guid("d141691c-112e-11ee-be56-0242ac120002"),
                            name = "Tecnología",
                            status = true
                        },
                        new
                        {
                            id = new Guid("d341691c-112e-11ee-be56-0242ac120004"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 291, DateTimeKind.Local).AddTicks(8951),
                            code = "Aut1234",
                            costcenterId = new Guid("d141691c-112e-11ee-be56-0242ac120003"),
                            name = "Nomina",
                            status = true
                        },
                        new
                        {
                            id = new Guid("d341691c-112e-11ee-be56-0242ac120005"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 291, DateTimeKind.Local).AddTicks(8957),
                            code = "Aut1233",
                            costcenterId = new Guid("d141691c-112e-11ee-be56-0242ac120004"),
                            name = "Logistica",
                            status = true
                        });
                });

            modelBuilder.Entity("webapi.Models.tblCostCenter", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("CentrCostos", (string)null);

                    b.HasData(
                        new
                        {
                            id = new Guid("d141691c-112e-11ee-be56-0242ac120002"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 291, DateTimeKind.Local).AddTicks(8017),
                            code = "Cc1234",
                            name = "Gerencia TI",
                            status = true
                        },
                        new
                        {
                            id = new Guid("d141691c-112e-11ee-be56-0242ac120003"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 291, DateTimeKind.Local).AddTicks(8026),
                            code = "Cc1235",
                            name = "Gerencia Financier",
                            status = true
                        },
                        new
                        {
                            id = new Guid("d141691c-112e-11ee-be56-0242ac120004"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 291, DateTimeKind.Local).AddTicks(8030),
                            code = "Cc1234",
                            name = "Gerencia Logistica",
                            status = true
                        });
                });

            modelBuilder.Entity("webapi.Models.tblEmployee", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<Guid>("areaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("identification")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("professionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("id");

                    b.HasIndex("areaId");

                    b.HasIndex("professionId");

                    b.ToTable("Empelados", (string)null);

                    b.HasData(
                        new
                        {
                            id = new Guid("d441691c-112e-11ee-be56-0242ac120002"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 292, DateTimeKind.Local).AddTicks(1752),
                            address = "Carrera 54# 34-25",
                            age = 29,
                            areaId = new Guid("d341691c-112e-11ee-be56-0242ac120002"),
                            identification = "12365487",
                            name = "pepito Perez",
                            phone = "3016590141",
                            professionId = new Guid("d241691c-112e-11ee-be56-0242ac120002"),
                            user = "user1"
                        },
                        new
                        {
                            id = new Guid("d441691c-112e-11ee-be56-0242ac120003"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 292, DateTimeKind.Local).AddTicks(1765),
                            address = "Carrera 54# 34-25",
                            age = 30,
                            areaId = new Guid("d341691c-112e-11ee-be56-0242ac120004"),
                            identification = "32554544",
                            name = "Monica Tamayo",
                            phone = "3016590141",
                            professionId = new Guid("d241691c-112e-11ee-be56-0242ac120004"),
                            user = "user2"
                        },
                        new
                        {
                            id = new Guid("d441691c-112e-11ee-be56-0242ac120004"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 292, DateTimeKind.Local).AddTicks(1772),
                            address = "Carrera 54# 34-25",
                            age = 25,
                            areaId = new Guid("d341691c-112e-11ee-be56-0242ac120005"),
                            identification = "32774544",
                            name = "Carlos Perez",
                            phone = "3016590141",
                            professionId = new Guid("d241691c-112e-11ee-be56-0242ac120004"),
                            user = "user3"
                        },
                        new
                        {
                            id = new Guid("d441691c-112e-11ee-be56-0242ac120005"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 292, DateTimeKind.Local).AddTicks(1779),
                            address = "Carrera 54# 34-25",
                            age = 40,
                            areaId = new Guid("d341691c-112e-11ee-be56-0242ac120004"),
                            identification = "125554544",
                            name = "Mario Castro",
                            phone = "3016590141",
                            professionId = new Guid("d241691c-112e-11ee-be56-0242ac120004"),
                            user = "user4"
                        },
                        new
                        {
                            id = new Guid("d441691c-112e-11ee-be56-0242ac120006"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 292, DateTimeKind.Local).AddTicks(1786),
                            address = "Carrera 54# 34-25",
                            age = 20,
                            areaId = new Guid("d341691c-112e-11ee-be56-0242ac120005"),
                            identification = "1254895444",
                            name = "Jose Peña",
                            phone = "3016590141",
                            professionId = new Guid("d241691c-112e-11ee-be56-0242ac120004"),
                            user = "user5"
                        });
                });

            modelBuilder.Entity("webapi.Models.tblProfession", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("Prefesion", (string)null);

                    b.HasData(
                        new
                        {
                            id = new Guid("d241691c-112e-11ee-be56-0242ac120002"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 291, DateTimeKind.Local).AddTicks(6011),
                            code = "Aut1234",
                            name = "Desarrollador",
                            status = true
                        },
                        new
                        {
                            id = new Guid("d241691c-112e-11ee-be56-0242ac120003"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 291, DateTimeKind.Local).AddTicks(6036),
                            code = "Aut1235",
                            name = "Coordinador",
                            status = true
                        },
                        new
                        {
                            id = new Guid("d241691c-112e-11ee-be56-0242ac120004"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 291, DateTimeKind.Local).AddTicks(6040),
                            code = "Aut1234",
                            name = "Analista",
                            status = true
                        },
                        new
                        {
                            id = new Guid("d241691c-112e-11ee-be56-0242ac120005"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 291, DateTimeKind.Local).AddTicks(6044),
                            code = "Aut1233",
                            name = "Ingeniero",
                            status = true
                        },
                        new
                        {
                            id = new Guid("d241691c-112e-11ee-be56-0242ac120006"),
                            CreationDate = new DateTime(2023, 6, 22, 14, 49, 13, 291, DateTimeKind.Local).AddTicks(6047),
                            code = "Aut1233",
                            name = "Gerente",
                            status = true
                        });
                });

            modelBuilder.Entity("webapi.Models.tblArea", b =>
                {
                    b.HasOne("webapi.Models.tblCostCenter", "costcenter")
                        .WithMany("area")
                        .HasForeignKey("costcenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("costcenter");
                });

            modelBuilder.Entity("webapi.Models.tblEmployee", b =>
                {
                    b.HasOne("webapi.Models.tblArea", "area")
                        .WithMany("employee")
                        .HasForeignKey("areaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webapi.Models.tblProfession", "profession")
                        .WithMany("employee")
                        .HasForeignKey("professionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("area");

                    b.Navigation("profession");
                });

            modelBuilder.Entity("webapi.Models.tblArea", b =>
                {
                    b.Navigation("employee");
                });

            modelBuilder.Entity("webapi.Models.tblCostCenter", b =>
                {
                    b.Navigation("area");
                });

            modelBuilder.Entity("webapi.Models.tblProfession", b =>
                {
                    b.Navigation("employee");
                });
#pragma warning restore 612, 618
        }
    }
}
